#!/usr/bin/env python3
"""
Merge CVAT annotations-only export with your local images into an Ultralytics OBB dataset.
Use when CVAT free plan doesn't let you export images.

Usage:
  python merge_cvat_export.py --cvat-export /path/to/cvat_export.zip --images /path/to/my_images --output ./dataset

  Or if you already unzipped CVAT export:
  python merge_cvat_export.py --cvat-export /path/to/unzipped_folder --images /path/to/my_images --output ./dataset

- cvat-export: zip or folder from CVAT (YOLO OBB 1.0). Must contain .txt label files (any subfolder).
- images: folder with your 56 images. Filenames must match CVAT (e.g. image_001.jpg → image_001.txt).
- output: dataset root to create (images/train, images/val, labels/train, labels/val, data.yaml).

Train/val split is 80/20 by default (--val-ratio 0.2). Random seed 42 for reproducibility.
"""

import argparse
import random
import shutil
import zipfile
from pathlib import Path


def find_label_stems(root: Path) -> list[str]:
    stems = []
    for p in root.rglob("*.txt"):
        stems.append(p.stem)
    return sorted(set(stems))


def find_image_for_stem(images_dir: Path, stem: str) -> Path | None:
    for ext in (".jpg", ".jpeg", ".png", ".bmp", ".webp"):
        p = images_dir / f"{stem}{ext}"
        if p.exists():
            return p
    return None


def get_label_path(cvat_root: Path, stem: str) -> Path | None:
    p = cvat_root / f"{stem}.txt"
    if p.exists():
        return p
    for p in cvat_root.rglob(f"{stem}.txt"):
        return p
    return None


def main():
    ap = argparse.ArgumentParser(description="Merge CVAT OBB export (no images) with local images.")
    ap.add_argument("--cvat-export", required=True, help="Path to CVAT export zip or unzipped folder")
    ap.add_argument("--images", required=True, help="Folder containing your images (names must match CVAT)")
    ap.add_argument("--output", required=True, help="Output dataset root (will create train/val)")
    ap.add_argument("--val-ratio", type=float, default=0.2, help="Fraction for validation (default 0.2)")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    cvat_path = Path(args.cvat_export)
    images_dir = Path(args.images)
    out_root = Path(args.output)

    if not images_dir.is_dir():
        raise SystemExit(f"--images must be a directory: {images_dir}")

    # Unzip if needed
    if cvat_path.suffix.lower() == ".zip":
        extract_dir = out_root / "_cvat_extract"
        extract_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(cvat_path) as z:
            z.extractall(extract_dir)
        cvat_root = extract_dir
    else:
        cvat_root = cvat_path
        if not cvat_root.is_dir():
            raise SystemExit(f"--cvat-export must be a zip or folder: {cvat_path}")

    stems = find_label_stems(cvat_root)
    if not stems:
        raise SystemExit("No .txt label files found in CVAT export.")

    # Match to images
    matched = []
    for stem in stems:
        img = find_image_for_stem(images_dir, stem)
        label = get_label_path(cvat_root, stem)
        if img and label:
            matched.append((stem, img, label))
        else:
            print(f"  Skip (no image or label): {stem}")

    if not matched:
        raise SystemExit(
            "No (image, label) pairs found. Ensure image filenames (without extension) match CVAT .txt names."
        )

    random.seed(args.seed)
    random.shuffle(matched)
    n_val = max(1, int(len(matched) * args.val_ratio))
    val_set = set(matched[i][0] for i in range(n_val))
    train_set = set(matched[i][0] for i in range(n_val, len(matched)))

    for sub in ("images/train", "images/val", "labels/train", "labels/val"):
        (out_root / sub).mkdir(parents=True, exist_ok=True)

    for stem, img_path, label_path in matched:
        if stem in val_set:
            img_dst = out_root / "images" / "val" / img_path.name
            lbl_dst = out_root / "labels" / "val" / f"{stem}.txt"
        else:
            img_dst = out_root / "images" / "train" / img_path.name
            lbl_dst = out_root / "labels" / "train" / f"{stem}.txt"
        shutil.copy2(img_path, img_dst)
        shutil.copy2(label_path, lbl_dst)

    # data.yaml
    path_abs = out_root.resolve()
    yaml = f"""# Generated by merge_cvat_export.py
path: {path_abs}
train: images/train
val: images/val

names:
  0: label
"""

    (out_root / "data.yaml").write_text(yaml, encoding="utf-8")

    if cvat_path.suffix.lower() == ".zip" and extract_dir.exists():
        shutil.rmtree(extract_dir)

    print(f"Done. Train: {len(train_set)}, Val: {len(val_set)}. Dataset: {out_root}")
    print(f"Run from yolo-obb-service: ./train.sh <path/to/data.yaml>")


if __name__ == "__main__":
    main()
